### ISSUE TITLE
Distribute Roles

### ISSUE THREAD

**Issue by shariq-h** [CSAllenISD/2023-ISP-iStudy#4]
The following roles need to be distributed to each group member.
 - Software Engineer 
 - QA Engineer
 - Project Manager 
 - Product Manager
 
I suggest both of us should take on the role of Software Engineer.

I would like to take on the role of Project Manager. Do you have a preference for the remaining 2?

**Comment by ishita-chow** [comment]
I can take on the roles of Product Manager and QA manager.
