### ISSUE TITLE
Set up a github.io or select a domain to purchase

### ISSUE THREAD

**Issue by shariq-h** [CSAllenISD/2023-ISP-iStudy#7]
We need to decide where the website will be hosted. I am having problems setting up a github.io folder, I think partly because the repo is under the CSAllenISD account. Should we look into a domain name?

**Comment by ishita-chow** [comment]
Hi i made a github.io... here's the link: https://ishita-chow.github.io/music-tracker.github.io/#home
It has my user name in the website link tho
